name: Build and Docker

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build and Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Caches
      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}"
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradle wrapper cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper
          key: "${{ runner.os }}-wrapper-${{ hashFiles('**/*.gradle') }}"
          restore-keys: |
            ${{ runner.os }}-wrapper-
      - name: Npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node cache
        uses: actions/cache@v4
        with:
          path: node
          key: "${{ runner.os }}-node-${{ hashFiles('**/*.gradle') }}"
          restore-keys: |
            ${{ runner.os }}-node-

      # JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      # Gradle build
      - name: Build with Gradle
        run: |
          ./gradlew classes testClasses --parallel --no-daemon
          ./gradlew build --no-daemon

      # Build Docker image
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: your-dockerhub-username/akhq:latest

      # Upload artifacts
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: build/libs/
